In [1]:
import os
import configparser

# Loading configurations
configParser = configparser.RawConfigParser()   
configFilePath = r'configuration.txt'
configParser.read(configFilePath)

insert_amd_env_vars =  int(configParser.get('COMMON', 'insert_amd_env_vars'))
HSA_OVERRIDE_GFX_VERSION =  configParser.get('COMMON', 'HSA_OVERRIDE_GFX_VERSION')
ROCM_PATH =  configParser.get('COMMON', 'ROCM_PATH')

if(insert_amd_env_vars != 0):
    os.environ["HSA_OVERRIDE_GFX_VERSION"] = HSA_OVERRIDE_GFX_VERSION
    os.environ["ROCM_PATH"] = ROCM_PATH
    
#import os
#os.environ["TF_CPP_MIN_LOG_LEVEL"] = "2"
#os.environ["AUTOGRAPH_VERBOSITY"] = "0"

In [2]:

import configparser

# Loading configurations
configParser = configparser.RawConfigParser()   
configFilePath = r'configuration.txt'
configParser.read(configFilePath)


evaluation_results_folder = configParser.get('evaluate_imagen', 'evaluation_results_folder')


datasetPathDatabase =  configParser.get('COMMON', 'test_datasetPathDatabase') + '/dataset.db'


cuda =  int(configParser.get('COMMON', 'cuda'))
cpus =  int(configParser.get('COMMON', 'cpus'))

In [3]:
#TODO document jupyter
import pickle
import sqlite3 as sl
import pandas as pd
import numpy as np
from PIL import Image

from textwrap import wrap
import os


import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

In [4]:
pd.set_option('display.max_columns', None)
pd.options.mode.chained_assignment = None

In [5]:
import lancedb
uri = datasetPathDatabase
db = lancedb.connect(uri)

vector_tbl = db.open_table("video_stage1")
videos = vector_tbl.to_pandas()
videos

,id,video_path,face_path,user,blurred_face_path,features_path,age,gender,ethnicity,vector,stage
0,0,/media/gamal/Passport/Datasets/Voxceleb2TestVi...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,id00017,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,26,Man,white,"[0.025988284, 0.002286622, 0.0059057563, 0.008...",1
1,1,/media/gamal/Passport/Datasets/Voxceleb2TestVi...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,id00061,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,31,Man,white,"[0.014909588, 0.01032118, 0.023922412, 0.00729...",1
2,2,/media/gamal/Passport/Datasets/Voxceleb2TestVi...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,id00081,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,28,Man,latino hispanic,"[0.017716583, 0.031231219, 0.0167601, 0.001974...",1
3,3,/media/gamal/Passport/Datasets/Voxceleb2TestVi...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,id00154,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,29,Man,middle eastern,"[0.015032666, 0.0020783008, 0.0017736976, -0.0...",1
4,4,/media/gamal/Passport/Datasets/Voxceleb2TestVi...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,id00419,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,38,Woman,white,"[0.014704544, -0.0042701024, 0.00066350354, 0....",1
...,...,...,...,...,...,...,...,...,...,...,...
113,113,/media/gamal/Passport/Datasets/Voxceleb2TestVi...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,id08552,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,26,Man,black,"[0.011644645, 0.006384785, 0.0013400487, 0.009...",1
114,114,/media/gamal/Passport/Datasets/Voxceleb2TestVi...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,id08696,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,27,Man,black,"[0.01209747, 0.011594199, 0.018551253, 0.01129...",1
115,115,/media/gamal/Passport/Datasets/Voxceleb2TestVi...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,id08701,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,44,Man,white,"[0.020973165, -0.011326933, -0.0015938727, 0.0...",1
116,116,/media/gamal/Passport/Datasets/Voxceleb2TestVi...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,id08911,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,26,Man,white,"[0.027417418, -0.0014938384, 0.011837885, 0.00...",1
117,117,/media/gamal/Passport/Datasets/Voxceleb2TestVi...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,id09017,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,/media/gamal/Passport/Datasets/VoxCeleb2Test/V...,24,Man,white,"[0.017197892, 0.0027304562, -0.003376963, 0.00...",1

In [6]:

i = 0
for index, video_row in videos.iterrows():
    features_path = video_row['features_path']
    user_true = video_row['user']
    face_emb_true = video_row['vector']

    with open(features_path, 'rb') as file1: 
        data = pickle.load(file1)
    face_emb = data['FACE_EMB_FROM_SPEECH']
    face_emb = pickle.loads(face_emb)
    face_emb = face_emb[0]
    print(face_emb)
    result = vector_tbl.search(face_emb).limit(10).to_df()

    match_1 = result.iloc[0]['user']
    match_2 = result.iloc[1]['user']
    match_3 = result.iloc[2]['user']
    match_4 = result.iloc[3]['user']
    match_5 = result.iloc[4]['user']
    match_6 = result.iloc[5]['user']
    match_7 = result.iloc[6]['user']
    match_8 = result.iloc[7]['user']
    match_9 = result.iloc[8]['user']
    match_10= result.iloc[9]['user']

    df_table = pd.DataFrame()
    df_table = df_table.append({'id': i , 'user_true':user_true,
                    'match_1':match_1,'match_2':match_2,'match_3':match_3,'match_4':match_4,'match_5':match_5,
                    'match_6':match_6,'match_7':match_7,'match_8':match_8,'match_9':match_9,'match_10':match_10,
                    'face_emb_true':face_emb_true,'face_emb_from_speech':face_emb
                    }, ignore_index=True)
    


    try:
        matches_tbl.add(df_table)
    except:
        db.drop_table('matches_s2FE', df_table)
        matches_tbl = db.create_table('matches_s2FE', df_table)

    i = i + 1

[ 0.01603739  0.01527959  0.00261578 ...  0.01750075 -0.00424344
 -0.00601482]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00418033  0.01795643  0.00383927 ... -0.00452246  0.00338028
 -0.00260203]
[ 0.00048053 -0.00872625  0.00261578 ... -0.00053466  0.00425285
 -0.00734076]
[ 0.00910151 -0.00844228  0.00261578 ...  0.01843742 -0.00250707
  0.02660928]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00044165  0.00310979  0.00261578 ... -0.00053466 -0.00424344
  0.01839138]
[ 0.010966   -0.02231301  0.00261578 ... -0.00684473  0.00786361
  0.02633814]
[ 0.00984996  0.01412925  0.00451856 ...  0.02619001  0.00996985
 -0.00288582]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[0.03088635 0.00417217 0.00261578 ... 0.02368825 0.00425285 0.02065695]
[0.02448967 0.00160739 0.00261578 ... 0.01583836 0.04673856 0.00062743]
[ 0.00213883  0.00177051  0.01637354 ...  0.03009064 -0.00250707
 -0.00397138]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00984996  0.00442429  0.00261578 ... -0.0043177   0.00425285
 -0.00100345]
[ 0.00597976  0.00322329  0.00261578 ... -0.01044461  0.00425285
 -0.00397138]
[ 0.00213883  0.00708513 -0.00374931 ... -0.00819348  0.00425285
 -0.0039733 ]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[0.03088635 0.01120787 0.00261578 ... 0.00238703 0.01180221 0.01825054]
[4.52028553e-03 1.41292481e-02 2.60966370e-03 ... 1.71718393e-02
 4.25285319e-03 7.99435555e-05]
[ 0.00048053 -0.00363145  0.00261578 ...  0.01075611  0.00191624
  0.0390416 ]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.010966    0.00088493 -0.00374931 ... -0.01115369  0.00164151
 -0.00644107]
[ 9.10151481e-03 -1.20830685e-02  4.32482921e-06 ...  1.42819621e-02
  4.25285319e-03  2.19578855e-02]
[ 0.00984996 -0.0026517   0.00261578 ...  0.00425821  0.00164151
  0.03006002]
[ 0.00984996  0.01412925  0.00261578 ... -0.0005379   0.00425285
  0.00608479]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[0.00984996 0.00900533 0.0004492  ... 0.02039817 0.00425285 0.01492713]
[ 0.00048053  0.00442429 -0.00374931 ...  0.007971    0.01326519
 -0.00118473]
[-0.00399017  0.01412925 -0.00472504 ... -0.00574071  0.00425285
 -0.00514262]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.01698047  0.01000464 -0.00374931 ... -0.00574071  0.00425285
  0.02493852]
[ 0.01698047  0.01218368 -0.01461282 ...  0.0016067  -0.00424344
  0.00949219]
[ 0.00754457 -0.00765997  0.00260966 ...  0.0407331   0.00843645
  0.00912482]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[0.00984996 0.00417217 0.00261578 ... 0.01602137 0.02679179 0.0033734 ]
[ 0.03142482  0.00322329  0.00261578 ... -0.011824   -0.00250707
 -0.00397138]
[ 0.01181855 -0.00045839 -0.00374931 ... -0.00975919  0.00425285
  0.00264324]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.0273182  -0.00385419  0.00261578 ...  0.00922368  0.05128953
  0.02968379]
[0.00048053 0.00037219 0.00261578 ... 0.007971   0.02225523 0.00109636]
[ 0.053812   -0.0017045  -0.00751848 ...  0.00190302  0.020905
  0.01683074]
[0.0573837  0.01241472 0.00260966 ... 0.02080605 0.00191624 0.02356735]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00048053 -0.01861063  0.00500426 ...  0.03890312  0.00775991
 -0.00601482]
[ 0.02022843  0.01412925  0.00128489 ... -0.00341714  0.00425285
  0.01839138]
[0.00048053 0.00442429 0.00261578 ... 0.00746504 0.00659175 0.00264324]
[ 0.053812    0.00058319  0.00260966 ... -0.01115369  0.00184248
  0.00081512]
[ 0.00048053  0.01412925 -0.00374931 ... -0.01115369  0.02225523
  0.03006002]
[ 0.04405399  0.00417217  0.01846307 ...  0.00238703  0.00425285
 -0.00397138]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00910151  0.00037219  0.00261578 ... -0.02127229  0.02613569
 -0.0039733 ]
[ 0.00303787  0.00905627 -0.00374931 ... -0.01115369  0.00425285
  0.00923299]
[ 0.01346241 -0.0001567   0.00798234 ...  0.00628356  0.04001909
 -0.00397138]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00984996  0.00417217  0.00261578 ... -0.02072703  0.00425285
 -0.00108295]
[0.0209701  0.0228433  0.00260966 ... 0.02112194 0.00996985 0.0390416 ]
[ 0.0127712  -0.0026517  -0.00374931 ...  0.04151125  0.0076187
 -0.00564777]
[ 0.00395465  0.01000464 -0.01461282 ... -0.00226546  0.00996985
 -0.00514262]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00395465  0.01000464 -0.01461282 ...  0.02829998  0.020905
 -0.00734076]
[ 0.00984996 -0.0001567   0.00261578 ...  0.01583836  0.01405392
  0.00704661]
[ 0.01910892 -0.00110944  0.00838695 ... -0.00686145 -0.00424344
 -0.00390691]
[ 0.00048053  0.01388567  0.00261578 ... -0.00033476  0.02748452
  0.00564979]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00048053  0.00708513  0.00261578 ... -0.00053466  0.00425285
 -0.0039733 ]
[ 0.01346241  0.0001401   0.00260966 ... -0.00033476  0.00425285
  0.02994104]
[0.00984996 0.00037219 0.00445608 ... 0.01962039 0.00425285 0.00923299]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[-3.38809330e-03 -1.70422171e-03  2.61578476e-03 ...  4.25821046e-03
  1.64151055e-03  7.99435555e-05]
[ 0.04406204  0.00442429  0.00261578 ... -0.00574071  0.00425285
 -0.00397138]
[0.00048053 0.0038813  0.00383927 ... 0.007971   0.03106086 0.01430906]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.0573837  -0.0001567  -0.00751848 ...  0.02573991 -0.00424344
  0.02026773]
[ 0.00048053  0.00417217  0.00261578 ...  0.01602137 -0.00250707
  0.00432359]
[ 0.0573837  -0.0136146   0.00237751 ...  0.01756084  0.020905
  0.00538058]
[ 0.0573837   0.01090704 -0.00048035 ... -0.00726878  0.00468835
 -0.00288582]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.02513558  0.00442429  0.00261578 ... -0.01286542  0.00425285
 -0.00118473]
[0.00984996 0.01412925 0.01741061 ... 0.02039817 0.00425285 0.02493852]
[ 0.00048053  0.01412925  0.00260966 ... -0.00341714  0.00425285
  0.00168393]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00984996 -0.0001567   0.00296782 ... -0.01167695  0.00425285
  0.00539692]
[ 0.00984996 -0.00088273  0.02154372 ...  0.00600034  0.02912834
  0.01492713]
[ 0.03909549 -0.00510174  0.00858821 ...  0.01289759  0.0076187
  0.00278245]
[-0.01227681  0.00708513  0.00046449 ... -0.01223716  0.00184248
  0.02968379]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[0.01910892 0.00417217 0.00260966 ... 0.01897708 0.00425285 0.00828124]
[ 0.00910151  0.00177051  0.0004492  ...  0.00093344 -0.00250707
 -0.00288582]
[ 0.00048053  0.01412925  0.00261578 ...  0.01878672  0.00425285
 -0.00319559]
[0.00213883 0.01412925 0.00261578 ... 0.007971   0.00425285 0.00608479]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 4.80532908e-04  6.11156505e-03 -1.06061352e-03 ...  9.69643022e-03
  9.96984945e-03  7.99435555e-05]
[ 3.71245309e-02  1.11754662e-02  1.48719586e-02 ... -4.31769502e-03
  4.25285319e-03  7.99435555e-05]
[0.00910151 0.00442429 0.0004492  ... 0.00093344 0.00164151 0.01492713]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00418033 -0.00844228  0.00260966 ... -0.01115369  0.00425285
  0.01197049]
[ 0.00984996 -0.0078144   0.0247995  ...  0.00209706 -0.00250707
  0.00539692]
[ 0.00984996 -0.00259865  0.00260966 ...  0.00512938  0.02031621
  0.02660928]
[ 0.0209701   0.01527959  0.00046449 ... -0.00686145  0.00425285
  0.01704546]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[0.00984996 0.01120787 0.00261578 ... 0.00425821 0.00425285 0.00168393]
[ 0.03466977 -0.00374923  0.00311691 ... -0.00053466  0.00425285
 -0.0039733 ]
[ 4.80532908e-04  4.17216789e-03  2.61578476e-03 ... -1.09407734e-02
  2.79058591e-02  7.99435555e-05]
[ 0.00048053 -0.00844228  0.00868146 ...  0.00238703  0.00695
 -0.0039733 ]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 3.71245309e-02  4.17216789e-03 -4.72504401e-03 ... -4.53810813e-03
  4.25285319e-03  7.99435555e-05]
[0.00910151 0.01412925 0.00260966 ... 0.007971   0.02031621 0.01509042]
[ 0.03714173 -0.0001567   0.00261578 ...  0.01962039  0.00425285
 -0.00397138]
[ 0.02023111 -0.00054728  0.01303868 ... -0.00453811  0.01841719
 -0.00012609]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00048053  0.00442429  0.00261578 ... -0.00819348 -0.00250707
 -0.00601482]
[ 0.00984996 -0.00054728  0.00260966 ... -0.01925666  0.00425285
  0.00806941]
[ 0.00984996  0.01412925  0.00261578 ... -0.00341714  0.0162969
 -0.00820217]
[ 8.75013542e-05 -1.70449610e-03 -9.22074541e-03 ...  7.03495685e-03
  2.09050020e-02  3.02051231e-02]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.03466977  0.00037219 -0.00374931 ...  0.00238703  0.00425285
 -0.01080077]
[0.00395465 0.00708513 0.00260966 ... 0.00190302 0.05128953 0.01825054]
[0.00910151 0.01412925 0.00383927 ... 0.02564534 0.00425285 0.01153488]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00984996 -0.00054728  0.00260966 ... -0.01093816  0.00425285
  0.01825054]
[ 0.00910151  0.00442429  0.00261578 ... -0.0043177   0.00425285
 -0.00236918]
[ 0.010966    0.00616043 -0.00106061 ... -0.01286542  0.00425285
  0.01825054]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00710523  0.00442429 -0.00472504 ... -0.015043   -0.00424344
  0.00264324]
[ 0.02022843 -0.01222047  0.02709376 ... -0.00199811 -0.00250707
 -0.00707108]
[ 4.80532908e-04  1.49997678e-02 -3.74930753e-03 ...  1.58383601e-02
  4.25285319e-03  7.99435555e-05]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.02022843 -0.01861063  0.00417652 ...  0.01100833  0.01966415
 -0.00643627]
[0.0170776  0.01848966 0.00261578 ... 0.00618432 0.00425285 0.03022699]
[ 0.053812   -0.00110944 -0.00106061 ... -0.00686145  0.0076187
  0.00278245]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.0273182   0.00708513  0.00260966 ...  0.03874758  0.0005856
 -0.00408775]
[ 0.00984996  0.00115966  0.01203514 ... -0.00866951  0.00425285
 -0.00397138]
[0.00984996 0.00417217 0.00261578 ... 0.02368825 0.00939731 0.00264324]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[0.00048053 0.00417217 0.00868146 ... 0.02435873 0.00164151 0.00264324]
[ 0.02702141  0.01795643 -0.00106061 ...  0.01000814  0.00223922
  0.00082829]
[ 0.03523753  0.00346897 -0.00374931 ... -0.00453811  0.00425285
  0.00264324]
[8.75013542e-05 2.43595452e-04 8.38694841e-03 ... 2.19160765e-02
 2.62844115e-02 2.15303171e-02]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.03712453  0.00417217  0.00261578 ... -0.00872834  0.00425285
 -0.00514262]
[ 0.00395465  0.00442429 -0.00472504 ... -0.00311842 -0.00424344
  0.02533386]
[ 0.03523753 -0.0001567   0.00868146 ...  0.02641042  0.00425285
  0.01828249]
[ 0.00754457  0.00160739  0.00261578 ... -0.00053466  0.04853412
  0.01323063]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[0.00048053 0.00037219 0.00260966 ... 0.00042416 0.00425285 0.00947045]
[ 0.00910151  0.00881532  0.00451856 ...  0.00922368  0.00425285
 -0.00319559]
[ 0.03142482  0.01388567  0.01203793 ... -0.01084685  0.00265661
  0.02599531]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

[ 0.00048053 -0.0001567   0.00260966 ...  0.02479347  0.00425285
  0.01839138]
[ 0.02227759 -0.00811086  0.01866837 ...  0.02191608  0.00775991
  0.02792731]

/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,
/tmp/ipykernel_392167/323930107.py:27: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_table = df_table.append({'id': i , 'user_true':user_true,

In [7]:
matches = matches_tbl.to_pandas()
matches

,id,user_true,match_1,match_2,match_3,match_4,match_5,match_6,match_7,match_8,match_9,match_10,face_emb_true,face_emb_from_speech
0,0,id00017,id07874,id04627,id05459,id06104,id03980,id03677,id08392,id07802,id07396,id01106,"[0.025988284, 0.002286622, 0.0059057563, 0.008...","[0.016037393361330032, 0.01527959480881691, 0...."
1,1,id00061,id07874,id04627,id06104,id07396,id03677,id05459,id08392,id01041,id01106,id08552,"[0.014909588, 0.01032118, 0.023922412, 0.00729...","[0.0041803280103274365, 0.017956431955099106, ..."
2,2,id00081,id07874,id04627,id03677,id06104,id05459,id01041,id01106,id08392,id07396,id04030,"[0.017716583, 0.031231219, 0.0167601, 0.001974...","[0.0004805329075073435, -0.00872624982148409, ..."
3,3,id00154,id07874,id04627,id03677,id06104,id01106,id05459,id01041,id07396,id08392,id04030,"[0.015032666, 0.0020783008, 0.0017736976, -0.0...","[0.009101514809299261, -0.008442276830060614, ..."
4,4,id00419,id07874,id03677,id04627,id07396,id06104,id01106,id05459,id01041,id08392,id02057,"[0.014704544, -0.0042701024, 0.00066350354, 0....","[0.0004416529638027506, 0.0031097889877855778,..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,113,id08552,id07874,id04627,id03677,id06104,id01041,id05459,id01106,id04656,id07396,id08392,"[0.011644645, 0.006384785, 0.0013400487, 0.009...","[0.0004805329075073435, 0.00037218835334190063..."
114,114,id08696,id07874,id04627,id05459,id06104,id03677,id07802,id08392,id07396,id04656,id03382,"[0.01209747, 0.011594199, 0.018551253, 0.01129...","[0.009101514809299261, 0.008815323002636433, 0..."
115,115,id08701,id07874,id04627,id05459,id08392,id06104,id04030,id07802,id03677,id07396,id01041,"[0.020973165, -0.011326933, -0.0015938727, 0.0...","[0.031424815533682704, 0.013885672576725483, 0..."
116,116,id08911,id07874,id03677,id04627,id06104,id01106,id01041,id07396,id03178,id05459,id03862,"[0.027417418, -0.0014938384, 0.011837885, 0.00...","[0.0004805329075073435, -0.0001566996988764063..."
117,117,id09017,id07874,id04627,id05459,id03677,id06104,id08392,id01041,id07396,id01106,id04253,"[0.017197892, 0.0027304562, -0.003376963, 0.00...","[0.0222775898873806, -0.008110856637358665, 0...."

In [8]:
from collections import Counter

def Most_Common(lst):
    data = Counter(lst)
    return data.most_common(1)[0][0]

def face_recog_first_n_matches(row,n):
    #print(n == 3)

    user = row['user_true']
    match_1 = row['match_1']
    match_2 = row['match_2']
    match_3 = row['match_3']
    match_4 = row['match_4']
    match_5 = row['match_5']
    match_6 = row['match_6']
    match_7 = row['match_7']
    match_8 = row['match_8']
    match_9 = row['match_9']
    match_10 = row['match_10']
    if(n==3):
        if(user == match_1 or user == match_2 or user == match_3):
            row['match_n_3'] = user
        else:
            lst = [match_1,match_2,match_3]
            row['match_n_3'] = Most_Common(lst)
    elif(n==5):
        if(user == match_1 or user == match_2 or user == match_3 or user == match_4 or user == match_5):
            row['match_n_5'] = user
        else:
            lst = [match_1,match_2,match_3,match_4,match_5]
            row['match_n_5'] = Most_Common(lst)
    elif(n==10):
        if(user == match_1 or user == match_2 or user == match_3 or user == match_4 or user == match_5 or
           user == match_6 or user == match_7 or user == match_8 or user == match_9 or user == match_10):
            row['match_n_10'] = user
        else:
            lst = [match_1,match_2,match_3,match_4,match_5,match_6,match_7,match_8,match_9,match_10]
            row['match_n_10'] = Most_Common(lst)
    else:
        raise Exception("n can only be 3,5 or 10") 
    
    #print(row)
    return row

In [9]:
matches = matches.apply(face_recog_first_n_matches,args=(3,),axis=1)
matches = matches.apply(face_recog_first_n_matches,args=(5,),axis=1)
matches = matches.apply(face_recog_first_n_matches,args=(10,),axis=1)
matches

,id,user_true,match_1,match_2,match_3,match_4,match_5,match_6,match_7,match_8,match_9,match_10,face_emb_true,face_emb_from_speech,match_n_3,match_n_5,match_n_10
0,0,id00017,id07874,id04627,id05459,id06104,id03980,id03677,id08392,id07802,id07396,id01106,"[0.025988284, 0.002286622, 0.0059057563, 0.008...","[0.016037393361330032, 0.01527959480881691, 0....",id07874,id07874,id07874
1,1,id00061,id07874,id04627,id06104,id07396,id03677,id05459,id08392,id01041,id01106,id08552,"[0.014909588, 0.01032118, 0.023922412, 0.00729...","[0.0041803280103274365, 0.017956431955099106, ...",id07874,id07874,id07874
2,2,id00081,id07874,id04627,id03677,id06104,id05459,id01041,id01106,id08392,id07396,id04030,"[0.017716583, 0.031231219, 0.0167601, 0.001974...","[0.0004805329075073435, -0.00872624982148409, ...",id07874,id07874,id07874
3,3,id00154,id07874,id04627,id03677,id06104,id01106,id05459,id01041,id07396,id08392,id04030,"[0.015032666, 0.0020783008, 0.0017736976, -0.0...","[0.009101514809299261, -0.008442276830060614, ...",id07874,id07874,id07874
4,4,id00419,id07874,id03677,id04627,id07396,id06104,id01106,id05459,id01041,id08392,id02057,"[0.014704544, -0.0042701024, 0.00066350354, 0....","[0.0004416529638027506, 0.0031097889877855778,...",id07874,id07874,id07874
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113,113,id08552,id07874,id04627,id03677,id06104,id01041,id05459,id01106,id04656,id07396,id08392,"[0.011644645, 0.006384785, 0.0013400487, 0.009...","[0.0004805329075073435, 0.00037218835334190063...",id07874,id07874,id07874
114,114,id08696,id07874,id04627,id05459,id06104,id03677,id07802,id08392,id07396,id04656,id03382,"[0.01209747, 0.011594199, 0.018551253, 0.01129...","[0.009101514809299261, 0.008815323002636433, 0...",id07874,id07874,id07874
115,115,id08701,id07874,id04627,id05459,id08392,id06104,id04030,id07802,id03677,id07396,id01041,"[0.020973165, -0.011326933, -0.0015938727, 0.0...","[0.031424815533682704, 0.013885672576725483, 0...",id07874,id07874,id07874
116,116,id08911,id07874,id03677,id04627,id06104,id01106,id01041,id07396,id03178,id05459,id03862,"[0.027417418, -0.0014938384, 0.011837885, 0.00...","[0.0004805329075073435, -0.0001566996988764063...",id07874,id07874,id07874
117,117,id09017,id07874,id04627,id05459,id03677,id06104,id08392,id01041,id07396,id01106,id04253,"[0.017197892, 0.0027304562, -0.003376963, 0.00...","[0.0222775898873806, -0.008110856637358665, 0....",id07874,id07874,id07874

In [10]:
matches['face_emb_true'].to_numpy()
np.stack( matches['face_emb_true'].to_numpy(), axis=1 )

array([[ 0.02598828,  0.01490959,  0.01771658, ...,  0.02097316,
         0.02741742,  0.01719789],
       [ 0.00228662,  0.01032118,  0.03123122, ..., -0.01132693,
        -0.00149384,  0.00273046],
       [ 0.00590576,  0.02392241,  0.0167601 , ..., -0.00159387,
         0.01183788, -0.00337696],
       ...,
       [-0.01383195, -0.01714237, -0.01335393, ..., -0.00107051,
        -0.01485614,  0.00104783],
       [ 0.00330518,  0.02425833,  0.00820924, ..., -0.00788718,
         0.00648804, -0.00286403],
       [ 0.01138555,  0.02333466,  0.02597708, ...,  0.00142075,
         0.0018512 ,  0.01255489]], dtype=float32)

In [11]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import mean_squared_error

y_actual = np.stack( matches['face_emb_true'].to_numpy(), axis=1 )
y_pred = np.stack( matches['face_emb_from_speech'].to_numpy(), axis=1 )

rms = mean_squared_error(y_actual, 
                         y_pred, squared=False)
print('Root mean squared error: ' + str(rms))


acc_1 = accuracy_score(matches['user_true'], matches['match_1'])
acc_3 = accuracy_score(matches['user_true'], matches['match_n_3'])
acc_5 = accuracy_score(matches['user_true'], matches['match_n_5'])
acc_10 = accuracy_score(matches['user_true'], matches['match_n_10'])
print('recall @ k = 1: ' + str(acc_1 * 100))
print('recall @ k = 3: ' + str(acc_3 * 100))
print('recall @ k = 5: ' + str(acc_5 * 100))
print('recall @ k = 10: ' + str(acc_10 * 100))

Root mean squared error: 0.012685744643974699
recall @ k = 1: 0.847457627118644
recall @ k = 3: 5.084745762711865
recall @ k = 5: 5.932203389830509
recall @ k = 10: 8.47457627118644